# Generated by Django 4.2.11 on 2025-12-12 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Env',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('test_type', models.CharField(default='http', max_length=20, null=True, verbose_name='环境值')),
                ('env', models.CharField(default='', max_length=50, null=True, verbose_name='环境值')),
                ('rerun', models.IntegerField(default=0, verbose_name='重跑次数')),
                ('is_clear_cache', models.BooleanField(default=False, verbose_name='是否清除缓存')),
                ('browser', models.CharField(default='', max_length=20, null=True, verbose_name='环境值')),
                ('base_url', models.CharField(default='', max_length=200, null=True, verbose_name='URL')),
                ('remote', models.CharField(default='', max_length=200, null=True, verbose_name='remote')),
                ('app_server', models.CharField(default='', max_length=100, null=True, verbose_name='APP服务')),
                ('app_info', models.CharField(default='{}', max_length=1000, null=True, verbose_name='APP信息')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('address', models.CharField(max_length=200, verbose_name='项目地址')),
                ('case_dir', models.CharField(default='test_dir', max_length=200, verbose_name='用例目录')),
                ('is_delete', models.BooleanField(default=False, null=True, verbose_name='删除')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('cover_name', models.CharField(default='', max_length=64, verbose_name='封面名称')),
                ('path_name', models.CharField(default='', max_length=64, verbose_name='封面路径名称')),
                ('test_num', models.IntegerField(default=0, verbose_name='测试文件数')),
                ('is_clone', models.IntegerField(default=0, verbose_name='克隆')),
                ('run_version', models.CharField(default='', max_length=200, verbose_name='当前运行版本（蓝绿运行）')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='团队名')),
                ('email', models.TextField(default='', null=True, verbose_name='团队邮箱')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
