# Generated by Django 4.0.2 on 2022-08-15 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Env',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('env', models.CharField(default='', max_length=50, null=True, verbose_name='环境值')),
                ('browser', models.CharField(default='', max_length=20, null=True, verbose_name='环境值')),
                ('base_url', models.CharField(default='', max_length=200, null=True, verbose_name='URL')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('address', models.CharField(max_length=200, verbose_name='项目地址')),
                ('case_dir', models.CharField(default='test_dir', max_length=200, verbose_name='用例目录')),
                ('is_delete', models.BooleanField(default=False, null=True, verbose_name='删除')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('cover_name', models.CharField(default='', max_length=64, verbose_name='封面名称')),
                ('path_name', models.CharField(default='', max_length=64, verbose_name='封面路径名称')),
            ],
        ),
    ]
