# Generated by Django 4.0.5 on 2022-06-10 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_name',
        ),
        migrations.AddField(
            model_name='project',
            name='address',
            field=models.CharField(default='', max_length=200, verbose_name='项目地址'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='is_delete',
            field=models.BooleanField(default=False, null=True, verbose_name='删除'),
        ),
    ]
