# Generated by Django 4.2.11 on 2024-07-30 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='env',
            name='remote',
            field=models.CharField(default='', max_length=200, null=True, verbose_name='remote'),
        ),
    ]
