# Generated by Django 4.0.6 on 2023-04-30 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='env',
            name='app_info',
            field=models.CharField(default='{}', max_length=1000, null=True, verbose_name='APP信息'),
        ),
        migrations.AddField(
            model_name='env',
            name='app_server',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='APP服务'),
        ),
        migrations.AddField(
            model_name='env',
            name='test_type',
            field=models.CharField(default='http', max_length=20, null=True, verbose_name='环境值'),
        ),
    ]
