# Generated by Django 4.0.4 on 2022-08-24 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_project', '0002_project_test_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_clone',
            field=models.IntegerField(default=0, verbose_name='克隆'),
        ),
    ]
