# Generated by Django 4.0.5 on 2022-06-10 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_project', '0002_remove_project_project_name_project_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='file',
        ),
        migrations.AddField(
            model_name='case',
            name='file_name',
            field=models.CharField(default='', max_length=200, verbose_name='文件名'),
        ),
        migrations.AddField(
            model_name='case',
            name='project',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app_project.project'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='File',
        ),
    ]
