# Generated by Django 4.2.11 on 2024-11-18 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_project', '0002_env_remote'),
    ]

    operations = [
        migrations.AddField(
            model_name='env',
            name='is_clear_cache',
            field=models.BooleanField(default=False, verbose_name='是否清除缓存'),
        ),
    ]
