# Generated by Django 3.0 on 2022-09-18 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_project', '0003_project_is_clone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='env',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
