# Generated by Django 4.0.5 on 2022-06-11 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_project', '0003_remove_case_file_case_file_name_case_project_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Case',
        ),
    ]
