# Generated by Django 4.0.2 on 2022-06-30 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_project', '0004_delete_case'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='cover_name',
            field=models.CharField(default='', max_length=64, verbose_name='封面名称'),
        ),
        migrations.AddField(
            model_name='project',
            name='path_name',
            field=models.CharField(default='', max_length=64, verbose_name='封面路径名称'),
        ),
    ]
