# Generated by Django 4.0.6 on 2022-09-22 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_project', '0004_auto_20220918_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='env',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
