# Generated by Django 4.0.6 on 2022-10-09 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_project', '0005_alter_env_id_alter_project_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='env',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='删除'),
        ),
    ]
