# Generated by Django 4.0.6 on 2022-11-20 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='email',
            field=models.TextField(default='', null=True, verbose_name='团队邮箱'),
        ),
    ]
