# Generated by Django 3.0 on 2022-09-18 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_team', '0002_auto_20220912_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
