# Generated by Django 3.0 on 2022-09-18 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_team', '0003_auto_20220918_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='删除'),
        ),
    ]
