# Generated by Django 4.0.5 on 2022-06-11 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_project', '0004_delete_case'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(default='', max_length=200, verbose_name='文件名')),
                ('class_name', models.CharField(default='', max_length=100, verbose_name='类名')),
                ('class_doc', models.TextField(blank=True, default='', null=True, verbose_name='类描述')),
                ('case_name', models.CharField(default='', max_length=100, verbose_name='方法名')),
                ('case_doc', models.TextField(blank=True, default='', null=True, verbose_name='方法描述')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_project.project')),
            ],
        ),
    ]
