# Generated by Django 4.0.2 on 2022-06-11 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_case', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='report',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='报告'),
        ),
    ]
