# Generated by Django 3.0 on 2022-09-18 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_case', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseresult',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
