# Generated by Django 4.2.11 on 2024-12-19 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_case', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='label',
            field=models.TextField(blank=True, default='', null=True, verbose_name='用例标签'),
        ),
        migrations.AddField(
            model_name='testcasetemp',
            name='label',
            field=models.TextField(blank=True, default='', null=True, verbose_name='用例标签'),
        ),
    ]
