# Generated by Django 4.0.6 on 2022-10-04 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_project', '0005_alter_env_id_alter_project_id'),
        ('app_case', '0003_alter_caseresult_id_alter_testcase_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='case_hash',
            field=models.CharField(default='', max_length=200, verbose_name='用例hash'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='case_name',
            field=models.CharField(default='', max_length=200, verbose_name='方法名'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='class_name',
            field=models.CharField(default='', max_length=200, verbose_name='类名'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='file_name',
            field=models.CharField(default='', max_length=500, verbose_name='文件名'),
        ),
        migrations.CreateModel(
            name='TestCaseTemp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(default='', max_length=500, verbose_name='文件名')),
                ('class_name', models.CharField(default='', max_length=200, verbose_name='类名')),
                ('class_doc', models.TextField(blank=True, default='', null=True, verbose_name='类描述')),
                ('case_name', models.CharField(default='', max_length=200, verbose_name='方法名')),
                ('case_doc', models.TextField(blank=True, default='', null=True, verbose_name='方法描述')),
                ('case_hash', models.CharField(default='', max_length=200, verbose_name='用例hash')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_project.project')),
            ],
        ),
    ]
