# Generated by Django 4.0.2 on 2022-07-01 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_case', '0004_testcase_run_time_alter_testcase_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='report',
            field=models.TextField(default='', null=True, verbose_name='报告内容'),
        ),
    ]
