# Generated by Django 4.0.2 on 2022-08-15 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_project', '0001_initial'),
        ('app_case', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200, verbose_name='任务名')),
                ('status', models.IntegerField(default=0, verbose_name='状态')),
                ('env', models.CharField(max_length=200, null=True, verbose_name='环境')),
                ('email', models.CharField(max_length=100, null=True, verbose_name='发送告警邮箱')),
                ('timed', models.CharField(default='', max_length=50, null=True, verbose_name='定时任务')),
                ('job_id', models.CharField(default='', max_length=100, null=True, verbose_name='定时任务ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_project.project')),
            ],
        ),
        migrations.CreateModel(
            name='TaskReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=500, verbose_name='名称')),
                ('report', models.TextField(default='', null=True, verbose_name='报告内容')),
                ('passed', models.IntegerField(default=0, verbose_name='通过用例')),
                ('error', models.IntegerField(default=0, verbose_name='错误用例')),
                ('failure', models.IntegerField(default=0, verbose_name='失败用例')),
                ('skipped', models.IntegerField(default=0, verbose_name='跳过用例')),
                ('tests', models.IntegerField(default=0, verbose_name='总用例数')),
                ('run_time', models.CharField(default='0', max_length=100, verbose_name='运行时长')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_task.testtask')),
            ],
        ),
        migrations.CreateModel(
            name='TaskCaseRelevance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_case.testcase')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_task.testtask')),
            ],
        ),
        migrations.CreateModel(
            name='ReportDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(default='', max_length=500, verbose_name='用例类称')),
                ('name', models.CharField(default='', max_length=500, verbose_name='用例名称')),
                ('run_time', models.CharField(default='0', max_length=100, verbose_name='运行时长')),
                ('doc', models.TextField(default='', null=True, verbose_name='用例描述')),
                ('system_out', models.TextField(default='', null=True, verbose_name='用例日志')),
                ('system_err', models.TextField(default='', null=True, verbose_name='用例错误')),
                ('failure_out', models.TextField(default='', null=True, verbose_name='用例错误')),
                ('error_out', models.TextField(default='', null=True, verbose_name='用例错误')),
                ('skipped_message', models.TextField(default='', null=True, verbose_name='用例错误')),
                ('skipped_msg', models.FloatField(default=0, verbose_name='运行时长')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_task.taskreport')),
            ],
        ),
    ]
