# Generated by Django 4.2.11 on 2024-11-25 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testtask',
            name='is_delete',
            field=models.BooleanField(default=False, null=True, verbose_name='删除'),
        ),
    ]
