# Generated by Django 4.2.11 on 2024-12-09 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_task', '0002_testtask_is_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testtask',
            name='timed',
            field=models.CharField(default='', max_length=500, null=True, verbose_name='定时任务'),
        ),
    ]
