# Generated by Django 4.0.6 on 2022-09-22 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_task', '0002_auto_20220918_2145'),
        ('app_task', '0002_remove_reportdetails_skipped_msg_and_more'),
    ]

    operations = [
    ]
