# Generated by Django 4.0.6 on 2022-09-22 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_task', '0003_merge_20220922_0030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testtask',
            name='env',
        ),
        migrations.AddField(
            model_name='testtask',
            name='env_id',
            field=models.IntegerField(null=True, verbose_name='环境ID'),
        ),
        migrations.AddField(
            model_name='testtask',
            name='team_id',
            field=models.IntegerField(null=True, verbose_name='团队ID'),
        ),
        migrations.AlterField(
            model_name='reportdetails',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='taskcaserelevance',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='taskreport',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='testtask',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
