# Generated by Django 4.0.6 on 2022-10-10 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_task', '0005_remove_testtask_job_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskcaserelevance',
            name='case',
        ),
        migrations.AddField(
            model_name='taskcaserelevance',
            name='case_hash',
            field=models.CharField(default='123', max_length=200, verbose_name='用例hash'),
            preserve_default=False,
        ),
    ]
